### PR TITLE
Use bash /dev/tcp for checking ssh availability

### PR DESCRIPTION
**Pull request by brennen**
May help a bit with #19.

- uses a couple of different `/dev/tcp` tricks to see if an ssh port is available
- adds a --debug just in case you don't want to fire the bootstrap every time
- `SSH_PORT` variable

Should be checked on a Mac before merge.

### CODE REVIEW

**Comment by toddtreece** [comment]
@brennen confirmed working on mac os x with a pi listening for ssh on port 23.

i had to fix one issue, so you might want to pull and double check on your machine before you merge:
```
todd:pi_bootstrap todd$ bash finder.sh 
finder.sh: line 9: [: ==: unary operator expected
```

**Comment by brennen** [comment]
> finder.sh: line 9: [: ==: unary operator expected

Cool.  I think `==` is just a synonym for `=`, may be a recent bashism.  Will tweak and merge.

**Comment by toddtreece** [comment]
@brennen the error was related to the left side being undefined. i wrapped it in quotes to fix the issue

**Comment by brennen** [comment]
Ah, gotcha.

**Pull request merged**
