### PR TITLE
Finder enhancements

### LINKED ISSUE #13: Add webIDE to main package
https://learn.adafruit.com/webide/overview

### LINKED ISSUE #17: Shutdown via Finder App
via [the beta blog post](https://www.adafruit.com/blog/2015/01/23/help-us-test-our-new-raspberry-pi-bootstrap-piday-raspberrypi/#comment-284445):

> The bootstrap works great on my Model B Rev 1.0. This program will be VERY handy. How about adding a convenient “Shutdown” button to gracefully shut down the Raspberry Pi?

### LINKED ISSUE #20: SSH Port Changed
I can't conect if I changed the default SSH port in the raspberry ssh server configuration

### PR DESCRIPTION
**Pull request by toddtreece**
## Adds
* Shutdown button  - fixes #17
* SSH Port Config - fixes #20 
* WebIDE install checkbox - fixes #13
* Changes default grunt task so changes to the node.js app don't require rebuilding during development
* Adds a sanity check to deploy script to make sure it is working with a copy of the repo
* Copy the latest versions of `finder.sh` & `install.sh` to `/var/packages` on deploy

## Testing 
Download [the v1.1-beta release](https://github.com/adafruit/Adafruit-Pi-Finder/releases/tag/v1.1-beta) to test

## Screenshot
screen shot 2015-01-26 at 6 23 03 pm

### CODE REVIEW

**Comment by toddtreece** [comment]
@brennen this is dependent on your `occi` webide config stuff, so just let me know when you've deployed it and I'll merge and publish the release.

**Comment by brennen** [comment]
Cool - it's deployable in its current state but I'd like to make it better
behaved in the case of webide=no and test a couple of things before we call
it another release.

Got some social obligations to go meet just now, but I'll wrap that up this
evening.

**Comment by toddtreece** [comment]
@brennen it can wait until tomorrow. i just wanted you to know where it stands in case you tried to run it or merge it

**Comment by brennen** [comment]
@toddtreece let's go ahead and go with this occi 0.4.0.  It'll change some over the course of the day, but this oughta work for the WebIDE checkbox to start.

**Comment by brennen** [comment]
(Deployed to repo.)

**Pull request merged**
